### ISSUE TITLE
Checksum not needed on local files

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flathub/com.sindresorhus.Caprine#1]
FYI, checksum isn't mandatory on local files, so you can safely remove [L82](https://github.com/flathub/com.sindresorhus.Caprine/blob/master/com.sindresorhus.Caprine.yaml#L82) and [L85](https://github.com/flathub/com.sindresorhus.Caprine/blob/master/com.sindresorhus.Caprine.yaml#L85).

I opened an issue because I'm unsure whether you prefer how it is now or don't mind changing to a more convenient approach.

**Comment by dusansimic** [comment]
@TheEvilSkeleton thanks for the note! I've removed the checksums now. I wasn't sure what the convention was (I saw some packages add checksums for local files and some not) 😁.
